server:
  port: 8080
  servlet:
    context-path: /bootcamp


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://hcxouvjlpqvvby:0bd9465c4cc0d042dcbea7ef1ddb1432b1620071baecc628ffa1a18a44f36805@ec2-100-24-139-146.compute-1.amazonaws.com:5432/daipj897r405js
    username: hcxouvjlpqvvby
    password: 0bd9465c4cc0d042dcbea7ef1ddb1432b1620071baecc628ffa1a18a44f36805
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Project developed during the Santander Dev Week | Full Stack
  version: 2.0
